apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster-name: local-cluster
    env: prod
    region: local
    type: hub
  name: hpl-app-of-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: local-cluster
    namespace: openshift-gitops
  project: default
  source:
    path: apps
    repoURL: https://github.com/fmt47/app-of-apps-agent
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
