apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster-name: local-cluster
    env: prod
    region: local
    tenant: petclinic
    type: hub
  name: hpl-helloworld
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: local-cluster
    namespace: hpl-helloworld
  project: default
  source:
    path: helloworld-argo
    repoURL: https://github.com/stolostron/application-lifecycle-samples
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
