apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd-agent: "true"
    cluster-name: yupchang-mc-0917
    env: prod
    region: local
    tenant: petclinic
    type: workload
  name: wpl-guestbook
  namespace: openshift-gitops
spec:
  destination:
    name: yupchang-mc-0917
    namespace: guestbook
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
