apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd-agent: "true"
    cluster-name: yupchang-mc-0917
    env: prod
    region: local
    tenant: petclinic
    type: workload
  name: wpl-helloworld
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: yupchang-mc-0917
    namespace: wpl-helloworld
  project: default
  source:
    path: helloworld-argo
    repoURL: https://github.com/stolostron/application-lifecycle-samples
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
